Refactor
YUKAI/MakerBoard pull request #1
Opened 2024-09-10 05:06 UTC by YoshinobuObata

Arduino library registoryに載せるライブラリです

ライブラリの推奨仕様ガイドライン
https://arduino.github.io/arduino-cli/1.0/library-specification/

keyoword.txtは特に不要そうでしたので追加してありません．
ライセンス周りやコメント文など確認お願いしたいです．

2024-09-10 13:24 UTC, sagiii commented
もし時間があれば、
ArduinoのAPIやexamplesのガイドラインに関する記事（[例](https://qiita.com/loonaifactory/items/1ddf0ec394ed42285b1b)や、[公式ドキュメント](https://docs.arduino.cc/learn/contributions/arduino-writing-style-guide/#writing-example-code)）を一読しつつ気になるところは直してみても良いかもです。参考にして見ても良いかもです。

2024-09-13 07:24 UTC, YoshinobuObata commented
ガイドラインに沿って修正しました

2024-09-17 04:34 UTC, KikoIshimoto approved these changes

2024-09-17 04:36 UTC, sagiii requested changes
@YoshinobuObata 
review投稿します（投稿できておらずすみません）。

2024-09-17 04:36 UTC, sagiii commented on README.md
> +[メイカーボード](https://prtimes.jp/main/html/rd/p/000000230.000015618.html)を簡単にテキストプログラミングするためのライブラリです．
@YoshinobuObata 暫定的にリリースにリンクしていて、追ってプロダクトページに置き換える想定であってますか（念の為）

2024-09-17 04:36 UTC, sagiii commented on examples/LED/LED.ino
> +    delay(1*1000UL);
cc: @KikoIshimoto 
この1000の定義方法はあまり見かけないような気もするのですが、一般的でしょうか？（Arduinoができる限り初学者に優しくというコンセプトのようなので曖昧性をあえて許容して、 `delay(1000);` でも良いようには思いました）

2024-09-17 04:36 UTC, sagiii commented on examples/RunMotor/RunMotor.ino
> +Servo Servo1;
@YoshinobuObata 
インスタンスの命名規則は揃えたほうが良さそうです。
`board` を正とするなら、 `servo1` 。

2024-09-17 04:36 UTC, sagiii commented on examples/RunMotor/RunMotor.ino
> +    motor1.set(100, motor1.FORWARD);    // Motor1 rotate forward. Object motor1 was included from MakerBoard.h
`motor1`は [Arduinoのガイドライン](https://qiita.com/loonaifactory/items/1ddf0ec394ed42285b1b#%E5%91%BD%E5%90%8D%E8%A6%8F%E7%B4%84)によれば `Motor1` のほうが良さそう。

2024-09-17 04:36 UTC, sagiii commented on src/MakerBoardMotor.cpp
> + */
VSCodeの補完に任せてDoxygen形式で統一するならしたほうが楽かもです。

2024-09-17 04:54 UTC, YoshinobuObata commented on examples/RunMotor/RunMotor.ino
> +    motor1.set(100, motor1.FORWARD);    // Motor1 rotate forward. Object motor1 was included from MakerBoard.h
インスタンスなので小文字かと思いましたが，グローバルなのでアッパーキャメルがいいですね

2024-09-17 05:04 UTC, YoshinobuObata commented on examples/RunMotor/RunMotor.ino
> +Servo Servo1;
変更しました

2024-09-17 05:05 UTC, YoshinobuObata commented on examples/LED/LED.ino
> +    delay(1*1000UL);
一般的だと思いますが，サンプルプログラムなので1000に直しました

2024-09-17 05:17 UTC, sagiii approved these changes

2024-09-17 05:18 UTC, merged